version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "orderservicedb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpass"
    ports:
      - "5432:5432"